[package]
name = "quickserve"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.5"
log = "0.4.22"
warp = "0.3.7"
tokio = { version = "1.39.2", features = ["full"] }
clap = { version = "4.5.16", features = ["derive"] }
